name: Publish snapshot package on commit to main
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Execute Gradle build and publish to Github Packages
        run: ./gradlew -Pversion=${{github.ref_name}} :core:build :core:publish
