name: Publish new version upon tag commit
on:
  push:
    tags:
      - '*'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build & shadowJar
        run: ./gradlew build shadowJar
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install JDeploy
        run: npm install
      - name: Set package version
        run: npm --no-git-tag-version version ${{github.ref_name}}
      - name: JDeploy Publish
        run: npx jdeploy publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
